version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: poster
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PW}"
    volumes:
      - commu:/var/lib/postgresql/data
volumes:
  commu: {}
