export const catagoryData = [
  { values: "선택" },
  { values: "앰비언트" },
  { values: "다크 앰비언트" },
  { values: "뉴에이지 음악" },
  { values: "베이스 음악" },
  { values: "퓨처 베이스" },
  { values: "일렉트로 하우스" },
  { values: "브레이크비트" },
  { values: "볼티모어 클럽" },
  { values: "저지 클럽" },
  { values: "빅 비트" },
  { values: "칠아웃" },
  { values: "다운템포" },
  { values: "사이키델릭 트랜스" },
  { values: "트립합" },
  { values: "디스코" },
  { values: "Hi-NRG" },
  { values: "유로비트" },
  { values: "유로댄스" },
  { values: "이탈로 디스코" },
  { values: "시티 팝" },
  { values: "포스트디스코" },
  { values: "드럼 앤 베이스" },
  { values: "리퀴드 펑크" },
  { values: "덥 음악" },
  { values: "일렉트로닉 록" },
  { values: "댄스록" },
  { values: "댄스 펑크" },
  { values: "일랙트로닉 팝" },
  { values: "디스코 폴로" },
  { values: "신스팝" },
  { values: "일렉트로클래시" },
  { values: "일렉트로팝" },
  { values: "인디 록" },
  { values: "크라우트록" },
  { values: "뉴 웨이브" },
  { values: "다크웨이브" },
  { values: "뉴 로맨티시즘" },
  { values: "포스트 록" },
  { values: "스페이스 록" },
  { values: "신스메탈" },
  { values: "그라인드코어" },
  { values: "일렉트로닉코어" },
  { values: "일렉트로니카" },
  { values: "프로그레시브" },
  { values: "민속 일렉트로니카" },
  { values: "쿠두루" },
  { values: "실험 음악" },
  { values: "포크트로니카" },
  { values: "블랙 미디" },
  { values: "일렉트로어쿠스틱" },
  { values: "애시드 재즈" },
  { values: "정글" },
  { values: "하드코어 테크노" },
  { values: "브레이크코어" },
  { values: "디지털 하드코어" },
  { values: "스피드코어" },
  { values: "유령론" },
  { values: "베이퍼웨이브" },
  { values: "힙합" },
  { values: "클라우드 랩" },
  { values: "크렁크" },
  { values: "이모 랩" },
  { values: "멈블 랩" },
  { values: "트랩" },
  { values: "드릴" },
  { values: "하우스" },
  { values: "애시드 하우스" },
  { values: "딥 하우스" },
  { values: "프렌치 하우스" },
  { values: "퓨처 하우스" },
  { values: "UK 하드하우스" },
  { values: "리듬 앤 블루스 및 솔 음악" },
  { values: "컨템퍼러리 알앤비" },
  { values: "네오 소울" },
  { values: "뉴 잭 스윙" },
  { values: "테크노" },
  { values: "트랜스 음악" },
  { values: "UK 개러지" },
  { values: "투스텝" },
  { values: "베이스라인" },
  { values: "브레이크스텝" },
  { values: "덥스텝" },
  { values: "퓨처 개러지" },
  { values: "그라임" },
  { values: "UK 펑키" },
  { values: "비디오 게임 음악" },
  { values: "칩튠" },
];
